### To Do List

- Read sales.csv
- Drop Columns (shipping addressz)
- Rename columns customaa
- calc total price from quantity x unit price
-

In [1]:
import pandas as pd

In [23]:
df = pd.read_csv('sales.csv')
df.head()

,sales_id,customaaaaa,productNAme,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address,shipping_addresszz,shipping_addressz
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082,Apt 953,Suite 51
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10,Apt 1926,Suite 61
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467,Apt 181,PO Box 29212
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236,Room 417,11th Floor
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343,Suite 99,Suite 77

In [ ]:
df.columns

Index(['sales_id', 'customaaaaa', 'productNAme', 'quantity', 'unit_price',
       'purchase_date', 'sales_representative', 'payment_method',
       'shipping_address', 'shipping_addresszz', 'shipping_addressz'],
      dtype='object')

In [24]:
df = df.drop(columns=['shipping_addresszz', 'shipping_addressz'])

In [25]:
df = df.rename(columns={'customaaaaa':'customer', 'productNAme': 'product_name'})
df.columns

Index(['sales_id', 'customer', 'product_name', 'quantity', 'unit_price',
       'purchase_date', 'sales_representative', 'payment_method',
       'shipping_address'],
      dtype='object')

In [15]:
df['total price'] = df['quantity'] * df['unit_price']

df.head()

,sales_id,customer,productNAme,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address,total price
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082,33855.87
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10,77763.95
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467,16864.59
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236,55134.30
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343,6535.55

In [ ]:
df.describe()

         sales_id    quantity  unit_price  total price
count  500.000000  500.000000   500.00000    500.00000
mean   250.500000   52.528000   508.45394  26875.54694
std    144.481833   28.548191   287.67060  22781.04650
min      1.000000    1.000000     2.51000     91.53000
25%    125.750000   29.000000   267.80250   7241.56750
50%    250.500000   53.000000   509.16000  21757.47000
75%    375.250000   77.000000   748.33250  40267.53750
max    500.000000  100.000000   999.90000  95115.29000

In [18]:
df.describe

<bound method NDFrame.describe of      sales_id            customer                    productNAme  quantity  \
0           1        Con Farlambe           Maple Chipotle Glaze        53
1           2     Greer Clappison         Vanilla Almond Granola        85
2           3        Dode Ascraft            Maple Almond Yogurt        57
3           4         Gaby Allard          Almond Joy Snack Bars        67
4           5       Herve Dunston  Smartphone Photography Tripod        71
..        ...                 ...                            ...       ...
495       496     Hollie Ainsbury               Tuscan Bean Soup        53
496       497  Hasheem Scammonden            Electric Egg Cooker        18
497       498     Poppy Alejandri               Kids' Trampoline        79
498       499    Renaldo Dimitrov     Self-Cleaning Water Bottle         3
499       500     Hussein Sivills      Cinnamon Roll Protein Bar        37

     unit_price purchase_date sales_representative payment_method  \
0        638.79     8/13/2020        Lionel Sandal           Cash
1        914.87      9/7/2022        Blisse Lutsch           Cash
2        295.87    12/25/2022         Saree Antrum           Cash
3        822.90      7/6/2020     Tierney Gorringe    Credit Card
4         92.05     3/16/2022   Idette Kobierzycki          Check
..          ...           ...                  ...            ...
495      318.09     5/12/2020         Daniela Duns           Cash
496      259.09     6/18/2020   Alastair Lightning           Cash
497      978.67    11/29/2021          Karim Cobby          Check
498      866.45     6/13/2022          Lexie Krier          Check
499      556.38     4/18/2020     Meade McGuinness    Credit Card

    shipping_address  total price
0          Room 1082     33855.87
1           Suite 10     77763.95
2          Room 1467     16864.59
3          Room 1236     55134.30
4           Room 343      6535.55
..               ...          ...
495         Suite 51     16858.77
496     PO Box 27826      4663.62
497     PO Box 87788     77314.93
498          Suite 7      2599.35
499        Room 1137     20586.06

[500 rows x 10 columns]>

In [26]:
df.head()

,sales_id,customer,product_name,quantity,unit_price,purchase_date,sales_representative,payment_method,shipping_address
0,1,Con Farlambe,Maple Chipotle Glaze,53,638.79,8/13/2020,Lionel Sandal,Cash,Room 1082
1,2,Greer Clappison,Vanilla Almond Granola,85,914.87,9/7/2022,Blisse Lutsch,Cash,Suite 10
2,3,Dode Ascraft,Maple Almond Yogurt,57,295.87,12/25/2022,Saree Antrum,Cash,Room 1467
3,4,Gaby Allard,Almond Joy Snack Bars,67,822.90,7/6/2020,Tierney Gorringe,Credit Card,Room 1236
4,5,Herve Dunston,Smartphone Photography Tripod,71,92.05,3/16/2022,Idette Kobierzycki,Check,Room 343

In [28]:
%pip install psycopg2 sqlalchemy

Collecting psycopg2
  Downloading psycopg2-2.9.12-cp313-cp313-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: sqlalchemy in c:\users\theitguy\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\users\theitguy\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\theitguy\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2-2.9.12-cp313-cp313-win_amd64.whl (2.8 MB)
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.8 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.8 MB 804.3 kB/s eta 0:00:03
   ------- -------------------------------- 0.5/2.8 MB 804.3 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.8 MB 703.9 kB/s eta 0:00:03
   ----------- ---------------------------- 0.8/2.8 MB 703.9 kB/s eta 0:00:03
   --------------- ------------------------ 1.0/2.8 MB 718.8 kB/s eta 0:00:03
   ------------------- -------------------- 1.3/2.8 MB 736.7 kB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.8 MB 736.7 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 760.0 kB/s eta 0:00:02
   ---------------------- ----------------- 1.6/2.8 MB 760.0 kB/s eta 0:00:02
   -------------------------- ------------- 1.8/2.8 MB 741.9 kB/s eta 0:00:02
   ------------------------------ --------- 2.1/2.8 MB 751.8 kB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.8 MB 751.8 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 727.1 kB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.8 MB 727.1 kB/s eta 0:00:01
   -------------------------------------- - 2.6/2.8 MB 727.2 kB/s eta 0:00:01
   ---------------------------------------- 2.8/2.8 MB 715.7 kB/s  0:00:04
Installing collected packages: psycopg2
Successfully installed psycopg2-2.9.12
Note: you may need to restart the kernel to use updated packages.

In [ ]:

from sqlalchemy import create_engine

port=5432
host = '127.0.0.1'
database_name='postgres'
user='postgres'
password='1234'

engine = create_engine(f'postgresql+psycopg2://{user}:{password}@{host}:{port}/{database_name}')

df.to_sql('sales', engine, if_exists='append', index=False)

500